#pragma once
#include "ECS.h"
// Functions for loading C++ implemented Lua functions into the given
// lua state.

struct lua_State;

namespace Sprocket {

class Window;

namespace lua {

class Script;

// Loads the given scene into the given lua state, and provides functions for
// creating/deleting entities as well as iterating entities. Also provides functions
// for access the singleton entity.
void load_registry_functions(lua::Script& script, spkt::registry& registry);

// Loads the given window into the given lua state, and provides functions for
// checking the current mouse position and the mouse offset from the previous frame.
void load_window_functions(lua::Script& script, Window& window);

// Loads a bunch of helper functions to ease entity manipulation.
void load_entity_transformation_functions(lua::Script& script);

// Loads functions for accessing and modifying components on entities. The implementation
// of this is generated by Datamatic.
void load_entity_component_functions(lua::Script& script);

}
}